In [1]:
from keras.datasets import imdb
from keras.utils.data_utils import get_file


Using Theano backend.


In [6]:
idx=imdb.get_word_index()
idx['bill']

985

In [7]:
idx_arr=sorted(idx,key=idx.get)
idx_arr[17629]

'breaker'

In [8]:
idx2word={v: k for k, v in idx.items()}
idx2word

{1: 'the',
 2: 'and',
 3: 'a',
 4: 'of',
 5: 'to',
 6: 'is',
 7: 'br',
 8: 'in',
 9: 'it',
 10: 'i',
 11: 'this',
 12: 'that',
 13: 'was',
 14: 'as',
 15: 'for',
 16: 'with',
 17: 'movie',
 18: 'but',
 19: 'film',
 20: 'on',
 21: 'not',
 22: 'you',
 23: 'are',
 24: 'his',
 25: 'have',
 26: 'he',
 27: 'be',
 28: 'one',
 29: 'all',
 30: 'at',
 31: 'by',
 32: 'an',
 33: 'they',
 34: 'who',
 35: 'so',
 36: 'from',
 37: 'like',
 38: 'her',
 39: 'or',
 40: 'just',
 41: 'about',
 42: "it's",
 43: 'out',
 44: 'has',
 45: 'if',
 46: 'some',
 47: 'there',
 48: 'what',
 49: 'good',
 50: 'more',
 51: 'when',
 52: 'very',
 53: 'up',
 54: 'no',
 55: 'time',
 56: 'she',
 57: 'even',
 58: 'my',
 59: 'would',
 60: 'which',
 61: 'only',
 62: 'story',
 63: 'really',
 64: 'see',
 65: 'their',
 66: 'had',
 67: 'can',
 68: 'were',
 69: 'me',
 70: 'well',
 71: 'than',
 72: 'we',
 73: 'much',
 74: 'been',
 75: 'bad',
 76: 'get',
 77: 'will',
 78: 'do',
 79: 'also',
 80: 'into',
 81: 'people',
 82: 'other',
 8

In [4]:
%matplotlib inline
from imp import reload
import utils; reload(utils)
from utils import *
from __future__ import division, print_function
import pickle as p

In [5]:
path=get_file('imdb_full.pkl',origin='https://s3.amazonaws.com/text-datasets/imdb_full.pkl',md5_hash='d091312047c43cf9e4e38fef92437263')

f=open(path,'rb')

(x_train,labels_train),(x_test,labels_test)=p.load(f)


In [9]:
len(x_train)

25000

In [8]:
#x_train[0]

In [9]:
' '.join([idx2word[o] for o in x_train[0]])

"bromwell high is a cartoon comedy it ran at the same time as some other programs about school life such as teachers my 35 years in the teaching profession lead me to believe that bromwell high's satire is much closer to reality than is teachers the scramble to survive financially the insightful students who can see right through their pathetic teachers' pomp the pettiness of the whole situation all remind me of the schools i knew and their students when i saw the episode in which a student repeatedly tried to burn down the school i immediately recalled at high a classic line inspector i'm here to sack one of your teachers student welcome to bromwell high i expect that many adults of my age think that bromwell high is far fetched what a pity that it isn't"

In [10]:
labels_train[:20]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [6]:
vocab_size=5000

In [16]:
trn=[np.array([i if i<vocab_size-1 else vocab_size-1 for i in s]) for s in x_train]
test=[np.array([i if i<vocab_size-1 else vocab_size-1 for i in s]) for s in x_test]

In [13]:
lens=np.array(list(map(len,trn)))

In [14]:
lens

array([138, 433, 149, ..., 292, 236, 140])

In [15]:
(lens.max(),lens.min(),lens.mean())

(2493, 10, 237.71364)

In [19]:
seq_len=500

In [17]:
trn

[array([4999,  309,    6,    3, 1069,  209,    9, 2175,   30,    1,  169,   55,   14,   46,   82,
        4999,   41,  393,  110,  138,   14, 4999,   58, 4477,  150,    8,    1, 4999, 4999,  482,
          69,    5,  261,   12, 4999, 4999, 2003,    6,   73, 2436,    5,  632,   71,    6, 4999,
           1, 4999,    5, 2004, 4999,    1, 4999, 1534,   34,   67,   64,  205,  140,   65, 1232,
        4999, 4999,    1, 4999,    4,    1,  223,  901,   29, 3024,   69,    4,    1, 4999,   10,
         694,    2,   65, 1534,   51,   10,  216,    1,  387,    8,   60,    3, 1472, 3724,  802,
           5, 3521,  177,    1,  393,   10, 1238, 4999,   30,  309,    3,  353,  344, 2989,  143,
         130,    5, 4999,   28,    4,  126, 4999, 1472, 2375,    5, 4999,  309,   10,  532,   12,
         108, 1470,    4,   58,  556,  101,   12, 4999,  309,    6,  227, 4187,   48,    3, 2237,
          12,    9,  215]),
 array([4999,   39, 4999,   14,  739, 4999, 3428,   44,   74,   32, 1831,   15,  150,   18

In [20]:
trn=sequence.pad_sequences(trn,maxlen=seq_len,value=0)
test=sequence.pad_sequences(test,maxlen=seq_len,value=0)

In [19]:
#trn[0]

In [20]:
##Simple Model

In [21]:
model=Sequential([Embedding(vocab_size,32,input_length=seq_len),Flatten(),Dense(100,activation='relu'),Dropout(0,7),Dense(1,activation='sigmoid')])

In [22]:
model.compile(loss='binary_crossentropy',optimizer=Adam(),metrics=['accuracy'])

In [23]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 500, 32)           160000    
_________________________________________________________________
flatten_1 (Flatten)          (None, 16000)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               1600100   
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 1,760,201
Trainable params: 1,760,201
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.fit(trn,labels_train,validation_data=(test,labels_test),nb_epoch=1,batch_size=10)

/usr/local/lib/python3.5/dist-packages/keras/models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 25000 samples, validate on 25000 samples
Epoch 1/1
25000/25000 [==============================] - 122s - loss: 0.3935 - acc: 0.8075 - val_loss: 0.3183 - val_acc: 0.8627


In [75]:
my_data=['my','balls','are','on','fire']

In [26]:
my_data

['the', 'worst', 'movie', 'in', 'history']

In [76]:
pre_data= np.array([idx[i] for i in my_data])

In [77]:
check=[np.array(pre_data)]

In [78]:
check=sequence.pad_sequences(check,maxlen=seq_len,value=0)

In [79]:
preds=model.predict(check)
preds

array([[ 0.2947]], dtype=float32)

In [36]:
model.save_weights('bias.h5')

In [ ]:
## Convolutional neural network

In [9]:
conv1=Sequential([Embedding(vocab_size,32,input_length=seq_len,dropout=0.2),
                  Dropout(0.2),
                  Convolution1D(64,5,border_mode='same',activation='relu'),
                  Dropout(0.2),
                  MaxPooling1D(),
                  Flatten(),
                  Dense(100,activation='relu'),
                  Dropout(0.7),
                  Dense(1,activation='sigmoid')
                 ])

/home/svatantra/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  """Entry point for launching an IPython kernel.
/home/svatantra/.local/lib/python3.5/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(64, 5, padding="same", activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
conv1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 500, 32)           160000    
_________________________________________________________________
dropout_1 (Dropout)          (None, 500, 32)           0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 500, 64)           10304     
_________________________________________________________________
dropout_2 (Dropout)          (None, 500, 64)           0         
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 250, 64)           0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 16000)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               1600100   
__________

In [17]:
conv1.compile(loss='binary_crossentropy',optimizer=Adam(),metrics=['accuracy'])

In [21]:
conv1.fit(trn,labels_train,validation_data=(test,labels_test),nb_epoch=1,batch_size=10)

/usr/local/lib/python3.5/dist-packages/keras/models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 25000 samples, validate on 25000 samples
Epoch 1/1
25000/25000 [==============================] - 575s - loss: 0.3956 - acc: 0.8068 - val_loss: 0.2655 - val_acc: 0.8889
